doctrine:
    dbal:
        # url: '%env(resolve:DATABASE_URL)%'
        dbname: '%env(resolve:DATABASE_NAME)%'
        host: '%env(resolve:DATABASE_HOST)%'
        port: '%env(resolve:DATABASE_PORT)%'
        user: '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASSWORD)%'
        driver: '%env(resolve:DATABASE_DRIVER)%'
        server_version: '%env(resolve:DATABASE_SERVER_VERSION)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Pantry:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'GreenHollow\Pantry\Entity'
                alias: Pantry
