nelmio_api_doc:
    documentation:
        info:
            title: Pantry API
            description: API supporting a service management web application for food pantry
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
